title: Purestrap
author:
    name: Attila Fulop

include: ["*.html"]

defaults:
  -
    scope:
        path: "docs"
        type: "pages"
    values:
        layout: "default"

kramdown:
    input: GFM
