title: Purestrap
author:
    name: Attila Fulop

include: ["*.html", "pages"]

defaults:
  -
    scope:
        path: "pages"
        type: "pages"
    values:
        layout: "default"

kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'
